\c leveltest

create table level_test
(
    id           bigint generated by default as identity
        primary key,
    answer       text        not null,
    category     varchar(50) not null
        constraint level_test_category_check
            check ((category)::text = ANY
        ((ARRAY ['ALGORITHM'::character varying, 'DATABASE'::character varying, 'DOCKER'::character varying, 'GIT'::character varying, 'JAVA'::character varying, 'NODEJS'::character varying, 'PYTHON'::character varying, 'REACT'::character varying, 'SPRING'::character varying, 'VUEJS'::character varying])::text[])),
    created_at   timestamp(6),
    difficulty   varchar(20) not null
        constraint level_test_difficulty_check
            check ((difficulty)::text = ANY
                   ((ARRAY ['HIGH'::character varying, 'MEDIUM'::character varying, 'LOW'::character varying])::text[])),
    must_include jsonb       not null,
    question     text        not null,
    updated_at   timestamp(6)
);

alter table level_test
    owner to lgcms;



create table member_answer
(
    id                   bigint generated by default as identity
        primary key,
    concept_analyses     text,
    created_at           timestamp(6),
    feedback             text,
    is_scored            boolean,
    member_answer        text,
    member_id            bigint not null,
    must_include_matched text,
    score                integer,
    scored_at            timestamp(6),
    scoring_details      text,
    scoring_model        varchar(255),
    updated_at           timestamp(6),
    question_id          bigint not null
        constraint fk2pefbfmbvj1ijp3kxvguwidcl
            references level_test
);

alter table member_answer
    owner to lgcms;

