\c consulting

create table batch_job_instance
(
    job_instance_id bigint       not null
        primary key,
    version         bigint,
    job_name        varchar(100) not null,
    job_key         varchar(32)  not null,
    constraint job_inst_un
        unique (job_name, job_key)
);

alter table batch_job_instance
    owner to lgcms;

create table batch_job_execution
(
    job_execution_id bigint    not null
        primary key,
    version          bigint,
    job_instance_id  bigint    not null
        constraint job_inst_exec_fk
            references batch_job_instance,
    create_time      timestamp not null,
    start_time       timestamp,
    end_time         timestamp,
    status           varchar(10),
    exit_code        varchar(2500),
    exit_message     varchar(2500),
    last_updated     timestamp
);

alter table batch_job_execution
    owner to lgcms;

create table batch_job_execution_context
(
    job_execution_id   bigint        not null
        primary key
        constraint job_exec_ctx_fk
            references batch_job_execution,
    short_context      varchar(2500) not null,
    serialized_context text
);

alter table batch_job_execution_context
    owner to lgcms;

create table batch_job_execution_params
(
    job_execution_id bigint       not null
        constraint job_exec_params_fk
            references batch_job_execution,
    parameter_name   varchar(100) not null,
    parameter_type   varchar(100) not null,
    parameter_value  varchar(2500),
    identifying      char         not null
);

alter table batch_job_execution_params
    owner to lgcms;

create table batch_step_execution
(
    step_execution_id  bigint       not null
        primary key,
    version            bigint       not null,
    step_name          varchar(100) not null,
    job_execution_id   bigint       not null
        constraint job_exec_step_fk
            references batch_job_execution,
    create_time        timestamp    not null,
    start_time         timestamp,
    end_time           timestamp,
    status             varchar(10),
    commit_count       bigint,
    read_count         bigint,
    filter_count       bigint,
    write_count        bigint,
    read_skip_count    bigint,
    write_skip_count   bigint,
    process_skip_count bigint,
    rollback_count     bigint,
    exit_code          varchar(2500),
    exit_message       varchar(2500),
    last_updated       timestamp
);

alter table batch_step_execution
    owner to lgcms;

create table batch_step_execution_context
(
    step_execution_id  bigint        not null
        primary key
        constraint step_exec_ctx_fk
            references batch_step_execution,
    short_context      varchar(2500) not null,
    serialized_context text
);

alter table batch_step_execution_context
    owner to lgcms;

create table complete_progress
(
    id                bigint generated by default as identity
        primary key,
    complete_progress bigint,
    member_id         bigint,
    title             varchar(255)
);

alter table complete_progress
    owner to lgcms;

create table daily_profit
(
    id        bigint generated by default as identity
        primary key,
    profit    bigint,
    day       timestamp(6),
    member_id bigint,
    title     varchar(255)
);

alter table daily_profit
    owner to lgcms;

create table enrollment
(
    id            bigint not null
        primary key,
    enrollment_at timestamp(6),
    lecture_id    varchar(255),
    student_id    bigint
);

alter table enrollment
    owner to lgcms;

create table lecture
(
    id           varchar(255) not null
        primary key,
    avg_rating   bigint,
    level        varchar(255),
    member_id    bigint,
    price        bigint,
    review_count bigint,
    title        varchar(255),
    total_amount bigint
);

alter table lecture
    owner to lgcms;

create table monthly_profit_status
(
    id        bigint generated by default as identity
        primary key,
    member_id bigint,
    profit    bigint,
    title     varchar(255)
);

alter table monthly_profit_status
    owner to lgcms;

create table progress
(
    id            bigint not null
        primary key,
    lecture_id    varchar(255),
    member_id     bigint,
    progress_rate bigint
);

alter table progress
    owner to lgcms;

create table progress_group
(
    id            bigint generated by default as identity
        primary key,
    member_id     bigint,
    rate_group    varchar(255),
    student_count bigint,
    title         varchar(255)
);

alter table progress_group
    owner to lgcms;

create table question
(
    id         bigint not null
        primary key,
    created_at timestamp(6),
    lecture_id varchar(255),
    member_id  bigint,
    title      varchar(255),
    updated_at timestamp(6)
);

alter table question
    owner to lgcms;

create table review
(
    id         bigint not null
        primary key,
    created_at timestamp(6),
    difficulty integer,
    lecture_id varchar(255),
    member_id  bigint,
    nickname   varchar(255),
    star       bigint,
    suggestion varchar(255),
    updated_at timestamp(6),
    usefulness integer
);

alter table review
    owner to lgcms;

create table student_lecture_count
(
    id                  bigint generated by default as identity
        primary key,
    lecture_count_group varchar(255),
    member_id           bigint,
    student_count       bigint
);

alter table student_lecture_count
    owner to lgcms;

