\c lesson

create table lesson
(
    id            varchar(255) not null
        primary key,
    created_at    timestamp(6),
    image_status  varchar(255)
        constraint lesson_image_status_check
            check ((image_status)::text = ANY
        ((ARRAY ['ENCODING'::character varying, 'DONE'::character varying, 'FAIL'::character varying])::text[])),
    information   varchar(2000),
    lecture_id    varchar(255),
    member_id     bigint,
    playtime      integer,
    thumbnail_url varchar(255),
    title         varchar(255),
    updated_at    timestamp(6),
    video_status  varchar(255)
        constraint lesson_video_status_check
            check ((video_status)::text = ANY
                   ((ARRAY ['ENCODING'::character varying, 'DONE'::character varying, 'FAIL'::character varying])::text[])),
    video_url     varchar(255)
);

alter table lesson
    owner to lgcms;

create table lesson_progress
(
    id             bigint generated by default as identity
        primary key,
    last_watched   integer,
    lecture_id     varchar(255),
    lesson_id      varchar(255),
    member_id      bigint,
    playtime       integer,
    total_playtime integer,
    updated_at     timestamp(6)
);

alter table lesson_progress
    owner to lgcms;

create table memo
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    lesson_id  varchar(255),
    member_id  bigint
);

alter table memo
    owner to lgcms;

create table memo_contents
(
    id      bigint generated by default as identity
        primary key,
    content varchar(5000),
    memo_id bigint
        constraint fk4bo561aoa3o8apih9nug2q1c0
            references memo
);

alter table memo_contents
    owner to lgcms;

create table quiz
(
    id         bigint generated by default as identity
        primary key,
    answer     char not null,
    created_at timestamp(6),
    lesson_id  varchar(255),
    question   varchar(255)
);

alter table quiz
    owner to lgcms;

create table quiz_answer
(
    id      bigint generated by default as identity
        primary key,
    content varchar(255),
    label   char not null,
    quiz_id bigint
        constraint fkoxi2td1x8cc3y4a0vlsg2hfnc
            references quiz
);

alter table quiz_answer
    owner to lgcms;

