\c payment

create table cart
(
    id            bigint generated by default as identity
        primary key,
    lecture_id    varchar(255),
    member_id     bigint,
    price         bigint,
    thumbnail_url varchar(255),
    title         varchar(255)
);

alter table cart
    owner to lgcms;


create table payment_status
(
    id         bigint generated by default as identity
        primary key,
    lecture_id varchar(255),
    member_id  bigint
);

alter table payment_status
    owner to lgcms;

