\c member

create table member
(
    member_id            bigint generated by default as identity
        primary key,
    desire_lecturer      boolean,
    email                varchar(255),
    nickname             varchar(255),
    role                 varchar(255)
        constraint member_role_check
            check ((role)::text = ANY
        ((ARRAY ['ADMIN'::character varying, 'LECTURER'::character varying, 'STUDENT'::character varying])::text[])),
    desire_lecturer_date timestamp(6)
);

alter table member
    owner to lgcms;

create table member_category
(
    member_category_id bigint generated by default as identity
        primary key,
    id                 bigint,
    name               varchar(255),
    member_id          bigint not null
        constraint fk8hm1bokubb1b6412fgb7jd77f
            references member
);

alter table member_category
    owner to lgcms;

create table social_member
(
    social_member_id bigint generated by default as identity
        primary key,
    social_type      varchar(255)
        constraint social_member_social_type_check
            check ((social_type)::text = 'GOOGLE'::text),
    sub              varchar(255),
    member_member_id bigint
        constraint fk5fsssjtn21l11m5l7i68qudea
            references member
);

alter table social_member
    owner to lgcms;

