\c lecture

create table lecture
(
    id             varchar(255) not null
        primary key,
    average_star   double precision,
    category       varchar(255),
    created_at     timestamp(6),
    description    varchar(255),
    image_status   varchar(255)
        constraint lecture_image_status_check
            check ((image_status)::text = ANY
        ((ARRAY ['ENCODING'::character varying, 'DONE'::character varying, 'FAIL'::character varying])::text[])),
    information    varchar(255),
    lecture_status varchar(255)
        constraint lecture_lecture_status_check
            check ((lecture_status)::text = ANY
                   ((ARRAY ['REJECTED'::character varying, 'APPROVED'::character varying, 'SUBMITTED'::character varying, 'HIDDEN'::character varying])::text[])),
    level          varchar(255),
    member_id      bigint,
    nickname       varchar(255),
    price          bigint,
    review_count   bigint,
    thumbnail      varchar(255),
    title          varchar(255),
    total_amount   bigint,
    updated_at     timestamp(6),
    video_status   varchar(255)
        constraint lecture_video_status_check
            check ((video_status)::text = ANY
                   ((ARRAY ['ENCODING'::character varying, 'DONE'::character varying, 'FAIL'::character varying])::text[]))
);

alter table lecture
    owner to lgcms;

create table lecture_question
(
    id         bigint generated by default as identity
        primary key,
    content    varchar(2000),
    lecture_id varchar(255),
    member_id  bigint,
    title      varchar(255)
);

alter table lecture_question
    owner to lgcms;

create table lecture_answer
(
    id                  bigint generated by default as identity
        primary key,
    content             varchar(2000),
    lecture_question_id bigint
        constraint fklp7ehcypacpyth5gkyu3paro9
            references lecture_question
);

alter table lecture_answer
    owner to lgcms;

create table student
(
    id        bigint generated by default as identity
        primary key,
    member_id bigint
);

alter table student
    owner to lgcms;

create table lecture_enrollment
(
    id                bigint generated by default as identity
        primary key,
    enrolled_at       timestamp(6),
    enrollment_status varchar(255)
        constraint lecture_enrollment_enrollment_status_check
            check ((enrollment_status)::text = ANY
        ((ARRAY ['EXPIRED'::character varying, 'ENROLLED'::character varying, 'SUBMITTED'::character varying])::text[])),
    member_id         bigint,
    lecture_id        varchar(255)
        constraint fk3p6tgpd0ceif2xskvn6b5b16r
            references lecture,
    student_id        bigint
        constraint fks9cxoj92taam56hl98em4smgl
            references student
);

alter table lecture_enrollment
    owner to lgcms;

create table review
(
    id         bigint generated by default as identity
        primary key,
    comment    varchar(255),
    create_at  timestamp(6),
    lecture_id varchar(255),
    member_id  bigint,
    nickname   varchar(255),
    star       integer,
    suggestion text
);

alter table review
    owner to lgcms;

create table review_content
(
    id        bigint generated by default as identity
        primary key,
    answer    integer,
    question  varchar(255),
    review_id bigint
        constraint fksv1cetgs7kxe6dt7y4qg1gp9x
            references review
);

alter table review_content
    owner to lgcms;

